name: H6060 Experiment 1 - XStream

on:
  workflow_dispatch:
    inputs:
      sca-eclipse-steady-enabled:
        description: Enable Eclipse Steady scan (SCA)
        type: boolean
        required: false
        default: true

      sca-snyk-enabled:
        description: Enable Snyk scan (SCA)
        type: boolean
        required: false
        default: true

      sca-owasp-dependency-check-enabled:
        description: Enable OWASP Dependency Check scan (SCA)
        type: boolean
        required: false
        default: true

      sca-grype-enabled:
        description: Enable Grype scan (SCA)
        type: boolean
        required: false
        default: true

      sast-sonarqube-enabled:
        description: Enable SonarQube scan (SAST)
        type: boolean
        required: false
        default: true

      sast-semgrep-enabled:
        description: Enable Semgrep scan (SAST)
        type: boolean
        required: false
        default: true

      sast-deepsource-enabled:
        description: Enable Deepsource scan (SAST)
        type: boolean
        required: false
        default: true

      sast-horusec-enabled:
        description: Enable Horusec scan (SAST)
        type: boolean
        required: false
        default: true

      sast-codeql-enabled:
        description: Enable CodeQL scan (SAST)
        type: boolean
        required: false
        default: true

      sast-snyk-code-enabled:
        description: Enable Snyk Code scan (SAST)
        type: boolean
        required: false
        default: true

defaults:
  run:
    shell: bash

permissions: write-all

jobs:
  build-application:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      # Branched from tag XSTREAM_1_4_15
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.14.0
        with:
          checkout-fetch-depth: 0
          java-distribution: temurin
          java-version: 17

      - name: Build Maven Application
        shell: bash
        run: mvn -Dmaven.test.skip=true clean install

      - name: Upload Maven Build Repository
        uses: actions/upload-artifact@v4
        with:
          name: maven-build
          if-no-files-found: error
          path: |
            xstream/target
            xstream-benchmark/target
            xstream-distribution/target
            xstream-hibernate/target
            xstream-jmh/target

      - name: Run Maven Tests
        if: ${{ inputs.sast-deepsource-enabled == true }}
        run: mvn -Dmaven.test.failure.ignore=true test

      - name: Upload Coverage XML Report
        if: ${{ inputs.sast-deepsource-enabled == true }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: xstream/target/site/jacoco/jacoco.xml
          if-no-files-found: error

      - name: Create Maven Dependency Tree
        uses: seansmith39/H6060-Experiment-Resources/.github/actions/maven/maven-dependency-tree@main

      - name: Create CycloneDX SBOM
        uses: seansmith39/H6060-Experiment-Resources/.github/actions/maven/maven-sbom@main

  java-scanning:
    name: Run SCA and SAST Java Scanning Workflow
    uses: seansmith39/H6060-Experiment-Resources/.github/workflows/experiment-1-java.yml@main
    needs: build-application
    secrets: inherit
    with:
      sca-eclipse-steady-enabled: ${{ inputs.sca-eclipse-steady-enabled }}
      sca-snyk-enabled: ${{ inputs.sca-snyk-enabled }}
      sca-owasp-dependency-check-enabled: ${{ inputs.sca-owasp-dependency-check-enabled }}
      sca-grype-enabled: ${{ inputs.sca-grype-enabled }}
      sast-codeql-enabled: ${{ inputs.sast-codeql-enabled }}
      sast-sonarqube-enabled: ${{ inputs.sast-sonarqube-enabled }}
      sast-semgrep-enabled: ${{ inputs.sast-semgrep-enabled }}
      sast-deepsource-enabled: ${{ inputs.sast-deepsource-enabled }}
      sast-horusec-enabled: ${{ inputs.sast-horusec-enabled }}
      sast-snyk-code-enabled: ${{ inputs.sast-snyk-code-enabled }}
      project-name: H6060-Java-XStream
      build-directory: ''
